AllCops:
  Includes:
    - '**/*.gemspec'
    - '**/Rakefile'
  Excludes:
    - 'bin/*'

SignalException:
  EnforcedStyle: only_raise

SymbolArray:
  Enabled: true

Documentation:
  Exclude:
    - spec/**/*.rb
    - lib/lugg/version.rb

LineLength:
  Exclude:
    - spec/**/*.rb
    - lib/lugg.rb

AndOr:
  Enabled: false

ClassLength:
  Exclude:
    - lib/lugg/runner.rb

MethodLength:
  Exclude:
    - lib/lugg/runner.rb
